# Generated by Django 5.0.6 on 2025-01-28 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('bus_type', models.CharField(choices=[('standard', 'Standard'), ('luxury', 'Luxury'), ('sleeper', 'Sleeper')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'ordering': ['bus_number'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.PositiveIntegerField(blank=True, help_text='Distance in miles', null=True)),
                ('estimated_duration', models.DurationField(help_text='HH:MM:SS format')),
            ],
            options={
                'ordering': ['origin', 'destination'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('fare', models.DecimalField(decimal_places=2, help_text='Base fare per seat', max_digits=8)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buses.route')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_available', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.schedule')),
            ],
            options={
                'ordering': ['schedule', 'seat_number'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['departure_time'], name='buses_sched_departu_244426_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['arrival_time'], name='buses_sched_arrival_2aa6c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('schedule', 'seat_number')},
        ),
    ]
