# Generated by Django 5.0.6 on 2025-01-28 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('buses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='buses.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', through='bookings.BookingSeat', to='buses.seat'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger', to='bookings.bookingseat'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingseat',
            unique_together={('booking', 'seat')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_time'], name='bookings_bo_booking_238b42_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
