# Generated by Django 5.0.6 on 2025-02-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_user_booking_full_name'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.PositiveIntegerField()),
                ('passenger_gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bookingseat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bookingseat',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingseat',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_booking_238b42_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_status_233e96_idx',
        ),
        migrations.AddField(
            model_name='bookedseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='buses.seat'),
        ),
        migrations.DeleteModel(
            name='BookingSeat',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together={('seat', 'booking')},
        ),
    ]
